# Generated by Django 4.1.1 on 2022-10-11 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=255, verbose_name='Apellidos')),
                ('cell_phone', models.CharField(max_length=10, unique=True, verbose_name='Telefono')),
                ('RFC', models.CharField(max_length=13, unique=True, verbose_name='RFC')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Correo Electronico')),
                ('street', models.CharField(max_length=255, verbose_name='Calle')),
                ('suburb', models.CharField(max_length=255, verbose_name='Colonia')),
                ('postal_code', models.CharField(max_length=5, verbose_name='Código Postal')),
                ('outdoor_num', models.CharField(blank=True, max_length=5, verbose_name='Numero Exterior')),
            ],
        ),
        migrations.CreateModel(
            name='driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del chofer')),
                ('last_name', models.CharField(max_length=255, verbose_name='Apellidos')),
                ('cell_phone', models.CharField(max_length=10, unique=True, verbose_name='Telefono')),
                ('tuition', models.CharField(max_length=8, verbose_name='Matricula')),
                ('type_vehicle', models.CharField(max_length=255, verbose_name='Tipo de vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Nombre del producto')),
                ('registry_resp', models.CharField(max_length=255, verbose_name='Responsable del registro')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='producto/', verbose_name='Imagen del prodcuto')),
                ('amount_kg', models.CharField(max_length=10, unique=True, verbose_name='Cantidad en kilo gramo')),
                ('price', models.IntegerField(default=0, verbose_name='Precio')),
            ],
        ),
        migrations.CreateModel(
            name='reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_reports', models.CharField(max_length=255, verbose_name='Nombre del reporte')),
            ],
        ),
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradename', models.CharField(max_length=255, verbose_name='Nombre Comercial')),
                ('business_name', models.CharField(max_length=255, verbose_name='Razon Social')),
                ('cell_phone', models.CharField(max_length=10, unique=True, verbose_name='Telefono')),
                ('RFC', models.CharField(max_length=13, unique=True, verbose_name='RFC')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Correo Electronico')),
                ('street', models.CharField(max_length=255, verbose_name='Calle')),
                ('suburb', models.CharField(max_length=255, verbose_name='Colonia')),
                ('postal_code', models.CharField(max_length=5, verbose_name='Código Postal')),
                ('outdoor_num', models.CharField(blank=True, max_length=5, verbose_name='Numero Exterior')),
            ],
        ),
        migrations.CreateModel(
            name='time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_in', models.DateTimeField(verbose_name='Fecha de ingreso')),
                ('date_out', models.DateTimeField(verbose_name='Fecha de salida')),
                ('arrival_date', models.DateTimeField(verbose_name='Fecha de llegada')),
            ],
        ),
        migrations.CreateModel(
            name='Historicalsupplier',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tradename', models.CharField(max_length=255, verbose_name='Nombre Comercial')),
                ('business_name', models.CharField(max_length=255, verbose_name='Razon Social')),
                ('cell_phone', models.CharField(db_index=True, max_length=10, verbose_name='Telefono')),
                ('RFC', models.CharField(db_index=True, max_length=13, verbose_name='RFC')),
                ('email', models.EmailField(db_index=True, max_length=100, verbose_name='Correo Electronico')),
                ('street', models.CharField(max_length=255, verbose_name='Calle')),
                ('suburb', models.CharField(max_length=255, verbose_name='Colonia')),
                ('postal_code', models.CharField(max_length=5, verbose_name='Código Postal')),
                ('outdoor_num', models.CharField(blank=True, max_length=5, verbose_name='Numero Exterior')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical supplier',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Historicalproduct',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Nombre del producto')),
                ('registry_resp', models.CharField(max_length=255, verbose_name='Responsable del registro')),
                ('image', models.TextField(blank=True, max_length=255, null=True, verbose_name='Imagen del prodcuto')),
                ('amount_kg', models.CharField(db_index=True, max_length=10, verbose_name='Cantidad en kilo gramo')),
                ('price', models.IntegerField(default=0, verbose_name='Precio')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical product',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Historicaldriver',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del chofer')),
                ('last_name', models.CharField(max_length=255, verbose_name='Apellidos')),
                ('cell_phone', models.CharField(db_index=True, max_length=10, verbose_name='Telefono')),
                ('tuition', models.CharField(max_length=8, verbose_name='Matricula')),
                ('type_vehicle', models.CharField(max_length=255, verbose_name='Tipo de vehiculo')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical driver',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Historicalclient',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=255)),
                ('name', models.CharField(max_length=50, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=255, verbose_name='Apellidos')),
                ('cell_phone', models.CharField(db_index=True, max_length=10, verbose_name='Telefono')),
                ('RFC', models.CharField(db_index=True, max_length=13, verbose_name='RFC')),
                ('email', models.EmailField(db_index=True, max_length=100, verbose_name='Correo Electronico')),
                ('street', models.CharField(max_length=255, verbose_name='Calle')),
                ('suburb', models.CharField(max_length=255, verbose_name='Colonia')),
                ('postal_code', models.CharField(max_length=5, verbose_name='Código Postal')),
                ('outdoor_num', models.CharField(blank=True, max_length=5, verbose_name='Numero Exterior')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical client',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
